--- #YAML:1.0
name: Math-SymbolicX-ParserExtensionFactory
version: 0.01
abstract: Generate Math::Symbolic parser extensions
license: perl
distribution_type: module
requires:
  Test::More: 0.44
  Data::Dumper: 0
  Memoize: 1.01
  Math::Symbolic: 0.129
  Parse::RecDescent: 0
dynamic_config: 0
