--- #YAML:1.0
name: Math-SymbolicX-ParserExtensionFactory
version: 1.00
author:
  - |-
    Steffen Mueller <symbolic-module at steffen-mueller dot net>
abstract: Generate parser extensions
license: perl
requires:
  Data::Dumper: 0
  Math::Symbolic: 0.161
  Memoize: 1.01
  Parse::RecDescent: 0
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
build_requires:
  Test::More: 0
provides:
  Math::SymbolicX::ParserExtensionFactory:
    file: lib/Math/SymbolicX/ParserExtensionFactory.pm
    version: 1.00
generated_by: Module::Build version 0.2608
